name: SFDX Test Run on Push 1

on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - main
        paths:
            - 'force-app/**'

jobs:
  test:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
      - name: sfdx-test-run
        run: sfdx force:apex:test:run -l RunLocalTests -w 30
      - name: Checkout Local Repo
        uses: actions/checkout@v2
      - name: sfdx-deploy-all
        run: sfdx force:source:deploy --sourcepath force-app
